name 'awesome_appliance_repair'
maintainer 'Me'
maintainer_email 'louie@louie.io'
license 'all_rights'
description 'Installs/Configures awesome_appliance_repair'
long_description 'Installs/Configures awesome_appliance_repair'
version '0.1.0'


depends 'apt', '~> 2.9.2'
depends 'firewall', '~> 2.4.0'
depends 'httpd', '~> 0.3.5'
depends 'mysql', '~> 7.0.0'
depends 'mysql2_chef_gem', '~> 1.0.1'
depends 'zipfile', '~> 0.1.0'